### ISSUE TITLE
Not working after Blizzard changes on DOM

### ISSUE THREAD

**Issue by TeKrop** [au5ton/overwatch-endorsement-api#1]
Blizzard recently changed the way data about endorsement is stored in DOM. Now, we only have a data-value attribute (float between 0 and 1) for each type of endorsement, not any data-total attribute anymore :(

Nice work on your script btw ^^

**Comment by au5ton** [comment]
Darn, I guess they caught on. Thanks for your help. I'm closing this issue request and archiving the repo.
